### ISSUE TITLE
two entities for on and off? (or up and down)

### ISSUE THREAD

**Issue by papo-o** [finity69x2/binary-control-button-row#2]
Hello,
is it possible to combine two entities into one line? one for on, one for off (or up / down
for two input_boolean  push on buttons

**Comment by finity69x2** [comment]
I'm not sure what you mean. Could you provide examples?

**Comment by papo-o** [comment]
![2020-09-07 21_27_21-Window](https://user-images.githubusercontent.com/25136535/92413730-b46e6480-f151-11ea-8d64-c92b432686e3.png)

**Comment by finity69x2** [comment]
you can't do it with my plugin but there are other custom lovelace plugins that could probably do what you want.

search for multiple entity row in HACS.

even then you will end up with 4 buttons using this plugin (one on & one odd for each entity). However I am working on a single toggle button control that you could use once it's done.

watch the other open issue here for the announcement when it's done. it should be out in a few days. I hope...

**Comment by papo-o** [comment]
thanks
