### ISSUE TITLE
[Feature Request] Single Button

### ISSUE THREAD

**Issue by apedance** [finity69x2/binary-control-button-row#3]
Hello,

thank you for this great addon.

Is it possible to show only one of the buttons (on/off) ?
That would be amazing.
Using it as a toggle.

Cheers.

**Comment by finity69x2** [comment]
sorry, no. not the way the control row works. I wouldn't be able to easily (or at all) make that an option so I would likely have to make a different plug-in for that.

**Comment by apedance** [comment]
I see.
Thank you for the quick answer.
finity69x2/toggle-control-button :)

**Comment by finity69x2** [comment]
> finity69x2/toggle-control-button :)

That's a pretty apt name. I'll use it! :)

**Comment by finity69x2** [comment]
Just an FYI...

I'm really sorry that it took so long to get to this but I finally finished the single button plugin you asked for.

you can find it here:

https://github.com/finity69x2/toggle-control-button-row

I'll close this one now.

Thanks for the suggestion. :)

**Comment by lebowski9000** [comment]
Nice work,
