### ISSUE TITLE
[Feature Request] Add Haptic Feedback

### ISSUE THREAD

**Issue by lebowski9000** [finity69x2/binary-control-button-row#4]
Would this be possible to add Haptic Feedback?

**Comment by finity69x2** [comment]
I'm pretty sure that isn't possible. At least with my knowledge.

**Comment by lebowski9000** [comment]
I should have clarified, haptic feedback for iOS. The default buttons in lovelace have them. Custom buttons also have the option to turn them off and on.

**Comment by rdebrock91** [comment]
I also would like to have this feature.
Is it possible you can implent this?
