### ISSUE TITLE
Adding slider

### ISSUE THREAD

**Issue by zigomatichub** [finity69x2/binary-control-button-row#6]
I would like to see if it's possible to integrate slider then no need to duplicate like here:

![image](https://user-images.githubusercontent.com/60198279/140613389-31d0cfd9-4b9a-4b37-bae5-9166bc235a7a.png)

Slider is coming from https://github.com/thomasloven/lovelace-slider-entity-row

I like to have on/off button which keep the last settings. I prefer this compare to the (low,medium,high) from light-brightness-preset-row options where if you click on off, there is no action.

**Comment by finity69x2** [comment]
This plug-in is a control row for binary entities which only have two states available (on/off) so adding a slider to the controls really doesn't make much sense to me.

You seem to be asking to incorporate the ability to control another entity/aspect (in this case brightness) into this control row. TBH, I'm not sure how that would be done. You might be able to use another plug-in (ex. multiple-entity row) but I don't think you can use a custom control row within another custom control row like that.
