### ISSUE TITLE
Feature Request: Ability for on/off to call services and read a binary sensor

### ISSUE THREAD

**Issue by bobloadmire** [finity69x2/binary-control-button-row#7]
Situation: I have a water heater that can only be activated via a service because you have to specify the length of time it runs, so I have a call service setup with 5 minutes. The water heater also has a binary sensor worksperfectly, when the water heater is circulating, the binary button updates, however when you click the button, it just brings up the sensor, so I would like the option for the button to call a service instead.

**Comment by finity69x2** [comment]
Sorry, but if I understand you right that is way beyond the scope of what this plugin should do.

It only turns on or off a binary type entity.

It can't call any other services.

And even if it was something I would be interested in doing I'm not sure how I would allow for entering the optional service data from the myriad services available in home assistant.

There might be other plugins you can use for that that already exist as custom plugins. If you search HACS you may find some there that do what you want.

**Comment by bobloadmire** [comment]
Ok thanks, I'll look around. I thought I'd ask since the default HA buttons have an option for service, so I though adding that option might be an easy thing. Thanks anyway!
