### ISSUE TITLE
does't work since Home Assistant 2023.5.0b0

### ISSUE THREAD

**Issue by bussio** [finity69x2/binary-control-button-row#8]
Logger: frontend.js.latest.202304280
Source: components/system_log/__init__.py:257 
First occurred: 09:36:20 (4 occurrences) 
Last logged: 09:37:06

http://192.168.178.42:8123/hacsfiles/binary-control-button-row/binary-control-button-row.js:9:38 ReferenceError: Can't find variable: Polymer

**Comment by terryhonn** [comment]
This looks to be because of https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

**Comment by apedance** [comment]
I suffer from the same issue. Really like the buttons provided by this integration.
Can't really find instructions to install polymer.

Any changes planned?

**Comment by kajmaj** [comment]
The same here.

**Comment by olaein** [comment]
> Logger: frontend.js.latest.202304280 Source: components/system_log/**init**.py:257 First occurred: 09:36:20 (4 occurrences) Last logged: 09:37:06
> 
> http://192.168.178.42:8123/hacsfiles/binary-control-button-row/binary-control-button-row.js:9:38 ReferenceError: Can't find variable: Polymer

Have same problem after uppgrade HA  any comment....

**Comment by finity69x2** [comment]
I'm working on it.

the polymer deprecation caught me off guard with such little notice and I have to figure out how to update it.

**Comment by apedance** [comment]
Thank you sir!

**Comment by finity69x2** [comment]
It should be fixed now.
